@startuml pedu
actor 利用者
actor 管理者

left to right direction
rectangle 利用開始 {
    利用者 -- (サインアップする)
    利用者 -- (PSNアカウントでサインアップする)
    利用者 -- (ニンテンドーアカウントでサインアップする)
}

rectangle プロフィール登録 {
    利用者 -- (プロフィールを登録する)
    利用者 -- (PSNアカウントと連動する)
    利用者 -- (ニンテンドーアカウントと連動する)
    利用者 -- (プレイしたことのあるゲームを登録する)
    利用者 -- (公開範囲を設定する)
    利用者 -- (推しのゲームを設定する)
    利用者 -- (推しのキャラを設定する)
}

rectangle フレンドを探す {
    利用者 -- (別の利用者を検索する)
    利用者 -- (別の利用者のプロフィールを閲覧する)
    利用者 -- (フレンド申請する)
}

rectangle チャット {
    利用者 -- (チャットするフレンドを選択する)
    利用者 -- (メッセージを送信する)
    利用者 -- (チャットを閲覧する)
}

@enduml