@startuml pedu
actor 学習者
actor 管理者

left to right direction
' 学習者
rectangle 学習 {
    学習者 -- (教材で学習する)
}
rectangle 試験 {
    学習者 -- (テスト問題を見る)
    学習者 -- (テスト問題に解答する)
    学習者 -- (点数を確認する)
    学習者 -- (模範解答を確認する)
}

' 管理者
rectangle 準備 {
    管理者 -- (対象者を管理する)
    管理者 -- (対象者に学習と試験の依頼を連絡する)
}

rectangle 結果確認 {
    管理者 -- (試験結果を確認する)
    管理者 -- (実施記録簿を出力する)
}

@enduml